import 'dotenv/config';
import express from 'express';
import crypto from 'node:crypto';
import path from 'node:path';
import fs from 'node:fs';
import mysql from 'mysql2/promise';
import { fileURLToPath } from 'node:url';

const here = path.dirname(fileURLToPath(import.meta.url));
const dbName = process.env.DB_NAME || 'intern_nexus';
const baseConfig = { host:process.env.DB_HOST || '127.0.0.1', port:Number(process.env.DB_PORT || 3306), user:process.env.DB_USER || 'root', password:process.env.DB_PASSWORD || '' };
let pool;
const hashPassword = password => { const salt=crypto.randomBytes(16).toString('hex'); return `${salt}:${crypto.scryptSync(password,salt,64).toString('hex')}`; };
const verifyPassword = (password, stored) => { const [salt,key]=stored.split(':'); return crypto.timingSafeEqual(Buffer.from(key,'hex'),crypto.scryptSync(password,salt,64)); };

async function initializeDatabase(){
  const connection=await mysql.createConnection(baseConfig);
  await connection.query(`CREATE DATABASE IF NOT EXISTS \`${dbName.replace(/`/g,'')}\` CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci`);
  await connection.end();
  pool=mysql.createPool({...baseConfig,database:dbName,waitForConnections:true,connectionLimit:10,namedPlaceholders:true});
  const statements=[
    `CREATE TABLE IF NOT EXISTS users (id VARCHAR(24) PRIMARY KEY,email VARCHAR(190) UNIQUE NOT NULL,password_hash VARCHAR(255) NOT NULL,role ENUM('intern','mentor','hr','admin') NOT NULL,name VARCHAR(120) NOT NULL,created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP)`,
    `CREATE TABLE IF NOT EXISTS sessions (token CHAR(64) PRIMARY KEY,user_id VARCHAR(24) NOT NULL,created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,expires_at TIMESTAMP NOT NULL,FOREIGN KEY(user_id) REFERENCES users(id) ON DELETE CASCADE)`,
    `CREATE TABLE IF NOT EXISTS tasks (id VARCHAR(24) PRIMARY KEY,title VARCHAR(255) NOT NULL,project VARCHAR(180),due_date VARCHAR(80),priority VARCHAR(20),status VARCHAR(30),progress INT DEFAULT 0,created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP)`,
    `CREATE TABLE IF NOT EXISTS leave_requests (id VARCHAR(24) PRIMARY KEY,type VARCHAR(60),from_date DATE,to_date DATE,days INT,status VARCHAR(30),reason TEXT,created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP)`,
    `CREATE TABLE IF NOT EXISTS candidates (id INT AUTO_INCREMENT PRIMARY KEY,name VARCHAR(140),role VARCHAR(120),college VARCHAR(180),email VARCHAR(190),score INT,status VARCHAR(30),created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP)`,
    `CREATE TABLE IF NOT EXISTS notifications (id INT AUTO_INCREMENT PRIMARY KEY,title VARCHAR(190),text TEXT,time_label VARCHAR(30),type VARCHAR(20),created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP)`,
    `CREATE TABLE IF NOT EXISTS attendance (id INT AUTO_INCREMENT PRIMARY KEY,user_id VARCHAR(24),attendance_date DATE,check_in TIME NULL,check_out TIME NULL,status VARCHAR(30),UNIQUE KEY one_day(user_id,attendance_date),FOREIGN KEY(user_id) REFERENCES users(id) ON DELETE CASCADE)`,
    `CREATE TABLE IF NOT EXISTS module_records (id CHAR(36) PRIMARY KEY,owner_id VARCHAR(24),kind VARCHAR(80),payload JSON,created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,FOREIGN KEY(owner_id) REFERENCES users(id) ON DELETE CASCADE)`
    ,`CREATE TABLE IF NOT EXISTS internship_programs (id INT AUTO_INCREMENT PRIMARY KEY,title VARCHAR(150),domain VARCHAR(100),duration VARCHAR(50),mode VARCHAR(40),location VARCHAR(100),fee DECIMAL(10,2),seats INT,deadline DATE,summary TEXT,technologies VARCHAR(255),status VARCHAR(20) DEFAULT 'Open')`
    ,`CREATE TABLE IF NOT EXISTS internship_applications (id VARCHAR(30) PRIMARY KEY,program_id INT,full_name VARCHAR(150),date_of_birth DATE NULL,gender VARCHAR(30),email VARCHAR(190),mobile VARCHAR(30),alternate_mobile VARCHAR(30),address TEXT,city VARCHAR(80),district VARCHAR(80),state VARCHAR(80),pin_code VARCHAR(15),college VARCHAR(180),university VARCHAR(180),department VARCHAR(120),degree VARCHAR(100),current_year VARCHAR(30),semester VARCHAR(30),registration_number VARCHAR(80),score VARCHAR(30),graduation_year VARCHAR(10),preferred_domain VARCHAR(100),duration VARCHAR(50),start_date DATE NULL,mode VARCHAR(40),location VARCHAR(100),experience TEXT,skills TEXT,interest_area TEXT,documents JSON,payment_status VARCHAR(30) DEFAULT 'Pending',hr_status VARCHAR(30) DEFAULT 'Under HR Review',approval_status VARCHAR(30) DEFAULT 'Pending',required_action VARCHAR(255) DEFAULT 'Await HR decision',created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,FOREIGN KEY(program_id) REFERENCES internship_programs(id))`
  ];
  for(const sql of statements) await pool.query(sql);
  await seedDatabase();
}

async function seedDatabase(){
  const [[{count}]]=await pool.query('SELECT COUNT(*) count FROM users');
  if(!count){
    const users=[['USR-I01','intern@jns.com','Intern@123','intern','Joshua Martin'],['USR-M01','mentor@jns.com','Mentor@123','mentor','Arjun Mehta'],['USR-H01','hr@jns.com','HR@123','hr','Maya Sharma'],['USR-A01','admin@jns.com','Admin@123','admin','Neha Kapoor']];
    for(const [id,email,password,role,name] of users) await pool.execute('INSERT INTO users(id,email,password_hash,role,name) VALUES(?,?,?,?,?)',[id,email,hashPassword(password),role,name]);
  }
  const [[taskCount]]=await pool.query('SELECT COUNT(*) count FROM tasks');
  if(!taskCount.count){
    const tasks=[['TSK-1042','Complete attendance API integration','Intern Nexus CRM','Today, 5:00 PM','High','In Progress',70],['TSK-1043','Polish dashboard responsive layout','Intern Nexus CRM','Tomorrow','Medium','Pending',25],['TSK-1038','Create leave workflow test cases','QA Automation','22 Jul','Low','Review',100],['TSK-1031','Authentication module','Intern Nexus CRM','18 Jul','High','Completed',100]];
    for(const row of tasks) await pool.execute('INSERT INTO tasks(id,title,project,due_date,priority,status,progress) VALUES(?,?,?,?,?,?,?)',row);
  }
  const [[leaveCount]]=await pool.query('SELECT COUNT(*) count FROM leave_requests');
  if(!leaveCount.count) await pool.query(`INSERT INTO leave_requests(id,type,from_date,to_date,days,status,reason) VALUES ('LV-2041','Sick Leave','2026-07-15','2026-07-15',1,'Approved','Medical appointment'),('LV-2052','Casual Leave','2026-07-25','2026-07-25',1,'Pending','Family function')`);
  const [[candidateCount]]=await pool.query('SELECT COUNT(*) count FROM candidates');
  if(!candidateCount.count) await pool.query(`INSERT INTO candidates(name,role,college,score,status) VALUES ('Aarav Patel','Frontend Intern','VIT Chennai',94,'Interview'),('Diya Nair','Data Science Intern','SRM University',91,'Shortlisted'),('Rohan Das','Backend Intern','Anna University',88,'Review'),('Ananya Rao','UI/UX Intern','MIT Manipal',86,'Selected')`);
  const [[notificationCount]]=await pool.query('SELECT COUNT(*) count FROM notifications');
  if(!notificationCount.count) await pool.query(`INSERT INTO notifications(title,text,time_label,type) VALUES ('Task deadline today','Attendance API integration is due at 5:00 PM.','12 min','red'),('Work log approved','Your 19 July work log was approved by Arjun.','1 hr','green'),('Meeting reminder','Sprint review begins at 3:00 PM in Orion Room.','2 hrs','blue'),('Workspace updated','Today: Bay 4, Desk 18.','Today','orange')`);
  await pool.query(`INSERT IGNORE INTO attendance(user_id,attendance_date,check_in,status) VALUES ('USR-I01','2026-07-20','09:03','Present')`);
  const [[programCount]]=await pool.query('SELECT COUNT(*) count FROM internship_programs');
  if(!programCount.count) await pool.query(`INSERT INTO internship_programs(title,domain,duration,mode,location,fee,seats,deadline,summary,technologies) VALUES ('Full-Stack Engineering','Web Development','8 weeks','Hybrid','Chennai',4999,24,'2026-08-15','Build production-ready web applications with guided engineering practice.','React, Node.js, Express, MySQL'),('AI & Machine Learning','Artificial Intelligence','10 weeks','Onsite','Chennai',5999,18,'2026-08-12','Learn applied machine learning through real datasets and mentor-led projects.','Python, Pandas, Scikit-learn, TensorFlow'),('UI/UX Product Design','Design','6 weeks','Hybrid','Chennai',3999,20,'2026-08-20','Research, prototype, test, and present thoughtful digital product experiences.','Figma, Research, Prototyping, Design Systems')`);
}

const app=express();
app.use(express.json({limit:'2mb'}));
const auth=async(req,res,next)=>{try{const token=(req.headers.authorization||'').replace(/^Bearer /,'');const [rows]=await pool.execute(`SELECT u.id,u.email,u.role,u.name FROM sessions s JOIN users u ON u.id=s.user_id WHERE s.token=? AND s.expires_at>NOW()`,[token]);if(!rows[0])return res.status(401).json({error:'Authentication required'});req.user=rows[0];req.token=token;next()}catch(e){next(e)}};
const notify=(title,text,type='green')=>pool.execute('INSERT INTO notifications(title,text,time_label,type) VALUES(?,?,?,?)',[title,text,'Now',type]);

app.get('/api/health',async(_req,res,next)=>{try{await pool.query('SELECT 1');res.json({status:'ok',service:'Intern Nexus API',database:'mysql',time:new Date().toISOString()})}catch(e){next(e)}});
app.get('/api/public/programs',async(_req,res,next)=>{try{const [rows]=await pool.query(`SELECT id,title,domain,duration,mode,location,fee,seats,DATE_FORMAT(deadline,'%Y-%m-%d') deadline,summary,technologies,status FROM internship_programs WHERE status='Open' ORDER BY id`);res.json(rows)}catch(e){next(e)}});
app.post('/api/public/applications',async(req,res,next)=>{try{const b=req.body;if(!b.full_name||!b.email||!b.mobile||!b.program_id)return res.status(400).json({error:'Name, email, mobile number, and internship program are required'});const [[{n}]]=await pool.query('SELECT COUNT(*) n FROM internship_applications');const id=`JNS-APP-${new Date().getFullYear()}-${String(n+1).padStart(5,'0')}`;const fields=['id','program_id','full_name','date_of_birth','gender','email','mobile','alternate_mobile','address','city','district','state','pin_code','college','university','department','degree','current_year','semester','registration_number','score','graduation_year','preferred_domain','duration','start_date','mode','location','experience','skills','interest_area','documents'];const values=[id,...fields.slice(1).map(k=>k==='documents'?JSON.stringify(b[k]||{}):(b[k]||null))];await pool.execute(`INSERT INTO internship_applications(${fields.join(',')}) VALUES(${fields.map(()=>'?').join(',')})`,values);res.status(201).json({success:true,applicationId:id,status:'Under HR Review',message:'Application submitted successfully'})}catch(e){next(e)}});
app.post('/api/public/applications/track',async(req,res,next)=>{try{const [rows]=await pool.execute(`SELECT a.id applicationId,a.full_name applicantName,p.title program,DATE_FORMAT(a.created_at,'%d %b %Y') applicationDate,a.payment_status paymentStatus,a.hr_status hrStatus,a.approval_status approvalStatus,a.required_action requiredAction FROM internship_applications a JOIN internship_programs p ON p.id=a.program_id WHERE a.id=? AND LOWER(a.email)=LOWER(?)`,[req.body.applicationId,req.body.email]);if(!rows[0])return res.status(404).json({error:'No application matches the provided reference and email'});res.json(rows[0])}catch(e){next(e)}});
app.post('/api/auth/login',async(req,res,next)=>{try{const {identity,password,role}=req.body;const [rows]=await pool.execute('SELECT * FROM users WHERE LOWER(email)=LOWER(?) AND role=?',[identity,role]);const user=rows[0];if(!user||!verifyPassword(password,user.password_hash))return res.status(401).json({error:'Invalid email, password, or role'});const token=crypto.randomBytes(32).toString('hex');await pool.execute('INSERT INTO sessions(token,user_id,expires_at) VALUES(?,?,DATE_ADD(NOW(), INTERVAL 12 HOUR))',[token,user.id]);res.json({token,user:{id:user.id,email:user.email,role:user.role,name:user.name}})}catch(e){next(e)}});
app.get('/api/auth/me',auth,(req,res)=>res.json({user:req.user}));
app.post('/api/auth/logout',auth,async(req,res,next)=>{try{await pool.execute('DELETE FROM sessions WHERE token=?',[req.token]);res.json({success:true})}catch(e){next(e)}});
app.get('/api/bootstrap',auth,async(_req,res,next)=>{try{const [tasks]=await pool.query('SELECT id,title,project,due_date due,priority,status,progress FROM tasks ORDER BY created_at DESC');const [leave]=await pool.query(`SELECT id,type,DATE_FORMAT(from_date,'%Y-%m-%d') \`from\`,DATE_FORMAT(to_date,'%Y-%m-%d') \`to\`,days,status,reason FROM leave_requests ORDER BY created_at DESC`);const [candidates]=await pool.query('SELECT id,name,role,college,email,score,status FROM candidates ORDER BY id');const [notifications]=await pool.query('SELECT title,text,time_label time,type FROM notifications ORDER BY id DESC LIMIT 30');const [attendance]=await pool.query(`SELECT DATE_FORMAT(attendance_date,'%Y-%m-%d') date,TIME_FORMAT(check_in,'%H:%i') checkIn,TIME_FORMAT(check_out,'%H:%i') checkOut,status FROM attendance ORDER BY attendance_date DESC`);res.json({tasks,leave,candidates,notifications,attendance})}catch(e){next(e)}});
app.post('/api/tasks',auth,async(req,res,next)=>{try{const [[{n}]]=await pool.query('SELECT COUNT(*) n FROM tasks');const task={id:`TSK-${1040+n}`,title:req.body.title,project:req.body.project,due:req.body.due,priority:req.body.priority,status:'Pending',progress:0};await pool.execute('INSERT INTO tasks(id,title,project,due_date,priority,status,progress) VALUES(?,?,?,?,?,?,?)',[task.id,task.title,task.project,task.due,task.priority,task.status,task.progress]);await notify('New task assigned',`${task.title} was added to ${task.project}.`);res.status(201).json(task)}catch(e){next(e)}});
app.patch('/api/tasks/:id',auth,async(req,res,next)=>{try{const [result]=await pool.execute('UPDATE tasks SET status=COALESCE(?,status),progress=COALESCE(?,progress) WHERE id=?',[req.body.status??null,req.body.progress??null,req.params.id]);if(!result.affectedRows)return res.status(404).json({error:'Task not found'});await notify('Task updated',`${req.params.id} is now ${req.body.status}.`);res.json({id:req.params.id,...req.body})}catch(e){next(e)}});
app.post('/api/leave',auth,async(req,res,next)=>{try{const [[{n}]]=await pool.query('SELECT COUNT(*) n FROM leave_requests');const days=Math.max(1,Math.round((new Date(req.body.to)-new Date(req.body.from))/86400000)+1),id=`LV-${2050+n}`;await pool.execute('INSERT INTO leave_requests(id,type,from_date,to_date,days,status,reason) VALUES(?,?,?,?,?,?,?)',[id,req.body.type,req.body.from,req.body.to,days,'Pending',req.body.reason]);await notify('Leave request submitted',`${req.body.type} request is awaiting approval.`);res.status(201).json({id,...req.body,days,status:'Pending'})}catch(e){next(e)}});
app.post('/api/candidates',auth,async(req,res,next)=>{try{if(!['hr','admin'].includes(req.user.role))return res.status(403).json({error:'HR access required'});const [r]=await pool.execute('INSERT INTO candidates(name,role,college,email,score,status) VALUES(?,?,?,?,82,\'Review\')',[req.body.name,req.body.role,req.body.college,req.body.email||null]);res.status(201).json({id:r.insertId,...req.body,score:82,status:'Review'})}catch(e){next(e)}});
app.patch('/api/candidates/:id',auth,async(req,res,next)=>{try{if(!['hr','admin'].includes(req.user.role))return res.status(403).json({error:'HR access required'});const [r]=await pool.execute('UPDATE candidates SET status=? WHERE id=?',[req.body.status,req.params.id]);if(!r.affectedRows)return res.status(404).json({error:'Candidate not found'});res.json({id:req.params.id,status:req.body.status})}catch(e){next(e)}});
app.post('/api/attendance/check-out',auth,async(req,res,next)=>{try{await pool.execute(`INSERT INTO attendance(user_id,attendance_date,check_in,check_out,status) VALUES(?,CURDATE(),NULL,CURTIME(),'Present') ON DUPLICATE KEY UPDATE check_out=CURTIME()`,[req.user.id]);const [[row]]=await pool.execute(`SELECT TIME_FORMAT(check_out,'%H:%i') checkOut FROM attendance WHERE user_id=? AND attendance_date=CURDATE()`,[req.user.id]);await notify('Attendance updated',`Check-out recorded at ${row.checkOut}.`);res.json(row)}catch(e){next(e)}});
app.post('/api/records',auth,async(req,res,next)=>{try{const id=crypto.randomUUID(),{kind='Record',...payload}=req.body;await pool.execute('INSERT INTO module_records(id,owner_id,kind,payload) VALUES(?,?,?,?)',[id,req.user.id,kind,JSON.stringify(payload)]);await notify('New workflow update',`${kind} was created successfully.`);res.status(201).json({id,kind,...payload})}catch(e){next(e)}});

const dist=path.resolve(here,'..','dist');
if(fs.existsSync(dist)){app.use(express.static(dist));app.get('/{*splat}',(_req,res)=>res.sendFile(path.join(dist,'index.html')))}
app.use((err,_req,res,_next)=>{console.error(err);res.status(500).json({error:'Internal server error'})});
const port=Number(process.env.PORT||3000);
initializeDatabase().then(()=>app.listen(port,'127.0.0.1',()=>console.log(`Intern Nexus API + MySQL running at http://127.0.0.1:${port}`))).catch(error=>{console.error('Database startup failed:',error.message);process.exit(1)});
