const nav=[
  {id:'home',label:'Home'},
  {id:'about',label:'About Us',items:['Company Overview','Mission & Vision','Leadership Team','Company Journey','Departments','Achievements','Office Gallery','Life at JNS']},
  {id:'services',label:'Services',items:['Web Development','Mobile App Development','Custom Software','Artificial Intelligence','Cloud & DevOps','Cybersecurity','UI/UX Design','Corporate Training','Request Quotation']},
  {id:'programs',label:'Internships',items:['Available Programs','Internship Domains','Eligibility Checker','Batch Schedule','Fees & Scholarships','Mentors','Apply for Internship','Track Application','Internship FAQ']},
  {id:'projects',label:'Projects',items:['Company Projects','Client Projects','Intern Projects','AI Projects','Web Applications','Mobile Applications','IoT Projects','Case Studies']},
  {id:'careers',label:'Careers',items:['Current Openings','Job Categories','Fresher Jobs','Campus Hiring','Life at JNS','Employee Benefits','Apply for Job','Track Candidate']},
  {id:'events',label:'Events',items:['Upcoming Events','Workshops','Webinars','Hackathons','Training Programs','Event Registration']},
  {id:'resources',label:'Resources',items:['Blogs','Tutorials','Technical Articles','Interview Preparation','Downloads','Company News']},
  {id:'contact',label:'Contact'},
  {id:'support',label:'Support',items:['Help Center','Raise an Enquiry','Track Support Request','Contact HR','Technical Support','Frequently Asked Questions']}
];
const money=n=>Number(n||0).toLocaleString('en-IN');
const icons={code:'</>',mobile:'▣',ai:'✦',cloud:'☁',shield:'◇',design:'◉',arrow:'↗'};
const pageButton=(id,label,cls='')=>`<button class="${cls}" data-page="${id}">${label}</button>`;

const shell=(state,body)=>`<div class="public public-site">
  <div class="announcement"><span>New</span> August 2026 internship applications are now open <button data-page="programs">Explore programs →</button><button class="announcement-close" aria-label="Dismiss announcement">×</button></div>
  <header class="site-header">
    <button class="public-brand site-logo" data-page="home" aria-label="JNS InternNexus home"><div class="brand-mark">J</div><div><strong>JNS</strong> InternNexus<small>Learn · Build · Succeed</small></div></button>
    <nav class="site-links" aria-label="Main navigation">${nav.map(item=>`<div class="nav-item"><button data-page="${item.id}" class="${state.publicPage===item.id?'active':''}">${item.label}${item.items?'<span class="chevron">⌄</span>':''}</button>${item.items?`<div class="mega-menu"><div><span class="mega-kicker">Explore ${item.label}</span><strong>${item.label} at JNS</strong><p>Discover every option, feature, and resource available in this module.</p><button class="mega-all" data-page="${item.id}">View ${item.label} overview →</button></div><div class="mega-links">${item.items.map((label,i)=>`<button data-page="${item.id}" data-section="${label}"><i>${String(i+1).padStart(2,'0')}</i><span>${label}</span></button>`).join('')}</div></div>`:''}</div>`).join('')}</nav>
    <div class="site-actions"><button class="header-icon" data-search aria-label="Search">⌕</button><button class="header-icon notification-button" data-notice aria-label="Notifications">♢<i>3</i></button><button class="btn primary apply-header" data-page="programs" data-section="Apply for Internship">Apply Now</button><button class="btn crm-button" data-crm>CRM Login</button><button class="site-menu" aria-label="Open menu" aria-expanded="false">☰</button></div>
  </header><main>${body}</main>
  <section class="site-cta"><div><span class="eyebrow light">Start your next chapter</span><h2>Ready to begin your<br>technology journey?</h2><p>Whether you’re building a career or a business, our team is ready to help.</p></div><div class="cta-actions">${pageButton('programs','Explore internships','btn light-btn')}${pageButton('contact','Talk to our team →','btn outline-light')}</div></section>
  <footer class="site-footer"><div class="footer-about"><div class="public-brand"><div class="brand-mark">J</div><div><strong>JNS</strong> InternNexus<small>by JNS Private Limited</small></div></div><p>Building dependable technology and career-ready talent through innovation, mentorship, and real-world experience.</p><div class="socials"><button aria-label="LinkedIn">in</button><button aria-label="GitHub">⌘</button><button aria-label="Instagram">◎</button><button aria-label="YouTube">▶</button></div></div><div><strong>Company</strong><button data-page="about">About us</button><button data-page="projects">Our work</button><button data-page="careers">Careers</button><button data-page="contact">Contact</button></div><div><strong>Programs</strong><button data-page="programs">Internships</button><button data-page="services">Services</button><button data-page="track">Track application</button><button data-crm>CRM portal</button></div><div><strong>Get in touch</strong><span>Chennai, Tamil Nadu</span><span>hello@jns.com</span><span>+91 98765 43210</span><span>Mon–Fri · 9 AM–6 PM</span></div></footer>
  <div class="footer-bottom"><span>© 2026 JNS Private Limited. All rights reserved.</span><span>Privacy Policy · Terms · Cookies · Accessibility</span></div>
  <button class="ai-fab" aria-label="Open JNS assistant"><b>✦</b><span>Ask JNS AI</span></button>
  <div class="search-modal" hidden><form><button type="button" class="search-close" aria-label="Close search">×</button><span>⌕</span><input autofocus placeholder="Search internships, services, projects…"><select aria-label="Search category"><option>All</option><option>Internships</option><option>Services</option><option>Projects</option><option>Careers</option><option>Events</option><option>Resources</option><option>FAQs</option></select><button class="btn primary">Search</button></form></div>
  <aside class="notice-panel" hidden><div><strong>Website notifications</strong><button data-close-notice>×</button></div>${[['New internship batch opened','Applications close 10 August.','Internship'],['AI workshop registration started','Only 18 seats remaining.','Event'],['Frontend Engineer vacancy','Applications are now open.','Career']].map(x=>`<article><span>${x[2]}</span><b>${x[0]}</b><p>${x[1]}</p><button>View notification →</button></article>`).join('')}<button class="mark-read">Mark all as read</button></aside>
</div>`;

const programCards=items=>`<div class="program-grid">${items.map((p,i)=>`<article class="program-card"><div class="program-cover cover-${i%3}"><span>${p.domain}</span><b>${p.duration}</b><div class="cover-art">${[icons.code,icons.ai,icons.shield][i%3]}</div></div><div class="program-body"><div class="program-meta"><span>● ${p.mode}</span><span>⌖ ${p.location}</span></div><h3>${p.title}</h3><p>${p.summary}</p><div class="program-tech">${String(p.technologies).split(',').slice(0,3).map(x=>`<i>${x.trim()}</i>`).join('')}</div><div class="program-foot"><div><small>Program fee</small><strong>₹${money(p.fee)}</strong></div><button class="circle-link" data-program="${p.id}" aria-label="View ${p.title}">↗</button></div></div></article>`).join('')}</div>`;

const services=[['code','Web Development','Fast, accessible websites and scalable web applications built for measurable growth.'],['mobile','Mobile Applications','Native and cross-platform experiences that feel effortless on every device.'],['ai','AI & Automation','Practical AI systems, intelligent assistants, analytics, and workflow automation.'],['cloud','Cloud Solutions','Secure deployment, migration, hosting, monitoring, and dependable infrastructure.'],['shield','Cybersecurity','Security assessments, protected authentication, monitoring, and expert guidance.'],['design','UI/UX Design','Research-led interfaces, prototypes, and design systems people enjoy using.']];
const projects=[['01','InternNexus CRM','A unified internship operations platform for people, progress, performance, and support.','CRM · Analytics · Automation'],['02','AI Workplace Assistant','An intelligent knowledge assistant that turns questions into accurate workplace actions.','AI · NLP · Search'],['03','Smart Asset Portal','Live asset allocation, maintenance, audit trails, and QR-powered handovers.','Cloud · Web · IoT']];

const home=state=>`<section class="site-hero"><div class="hero-glow"></div><div class="hero-copy"><span class="hero-kicker"><i></i> Technology solutions. Career transformation.</span><h1>Build what’s next.<br><em>Become who’s next.</em></h1><p>JNS InternNexus brings modern software solutions and industry-focused internships together—helping businesses innovate and learners become job-ready.</p><div class="hero-actions">${pageButton('services','Explore services →','btn primary')}${pageButton('programs','View internships','btn hero-secondary')}</div><div class="trust-row"><span><b>✓</b> Real-world projects</span><span><b>✓</b> Expert mentorship</span><span><b>✓</b> Verified outcomes</span></div></div><div class="hero-visual" aria-label="InternNexus platform preview"><div class="orbit orbit-one"></div><div class="orbit orbit-two"></div><div class="dashboard-preview"><div class="preview-bar"><span><i></i><i></i><i></i></span><b>InternNexus</b><em>● Live</em></div><div class="preview-layout"><aside><b>J</b>${['⌂','✓','◇','◷','▤'].map(x=>`<i>${x}</i>`).join('')}</aside><div><small>GOOD MORNING, ARUN</small><h3>Your internship overview</h3><div class="mini-stats"><span><b>94%</b>Attendance</span><span><b>12</b>Tasks done</span><span><b>78%</b>Progress</span></div><div class="mini-chart">${[45,72,57,88,68,94,80].map(x=>`<i style="height:${x}%"></i>`).join('')}</div></div></div></div><div class="float-card mentor"><span>AM</span><div><small>MENTOR REVIEW</small><b>Great progress!</b></div><i>✓</i></div><div class="float-card project"><span>◆</span><div><small>PROJECT STATUS</small><b>On track</b></div><strong>82%</strong></div></div></section>
<section class="impact-strip">${[['100+','Projects delivered'],['500+','Interns trained'],['15+','Technology domains'],['4.9/5','Learner satisfaction']].map(x=>`<div><strong>${x[0]}</strong><span>${x[1]}</span></div>`).join('')}</section>
<section class="section intro-section"><div class="intro-art"><div class="art-grid"></div><div class="experience-badge"><strong>8+</strong><span>Years of<br>combined expertise</span></div><div class="art-code"><small>BUILDING IMPACT</small><b>Ideas → Products</b><i>01 / 04</i></div></div><div class="intro-copy"><span class="eyebrow">About JNS Private Limited</span><h2>Technology with purpose.<br>Learning with direction.</h2><p>We are a technology and talent-development company that believes meaningful growth happens when people solve real problems. Our teams build reliable digital products while our internship programs turn classroom knowledge into professional capability.</p><div class="mission-row"><article><span>◎</span><div><h3>Our mission</h3><p>Create reliable solutions and practical learning experiences that move people and businesses forward.</p></div></article><article><span>↗</span><div><h3>Our vision</h3><p>Become the trusted bridge between technology innovation and emerging talent.</p></div></article></div>${pageButton('about','Discover our story →','text-arrow')}</div></section>
<section class="section services-section"><div class="section-heading"><div><span class="eyebrow">What we do</span><h2>Digital solutions designed<br>for real business impact.</h2></div><p>From first idea to successful launch, we bring strategy, design, engineering, and intelligent technology together.</p></div><div class="service-grid">${services.map(([icon,title,desc],i)=>`<article class="service-card"><span class="service-number">0${i+1}</span><div class="service-icon">${icons[icon]}</div><h3>${title}</h3><p>${desc}</p><button data-page="services">Learn more <b>↗</b></button></article>`).join('')}</div><div class="center-action">${pageButton('services','Explore all services →','btn dark-btn')}</div></section>
<section class="section programs-section"><div class="section-title-row"><div><span class="eyebrow">Featured programs</span><h2>Don’t just learn.<br>Build something that matters.</h2></div><div><p>Mentor-guided pathways with clear milestones, real deliverables, and outcomes you can prove.</p>${pageButton('programs','View all programs →','text-arrow')}</div></div>${programCards(state.programs.slice(0,3))}</section>
<section class="section projects-section"><div class="section-heading light-heading"><div><span class="eyebrow light">Selected work</span><h2>Ideas transformed into<br>useful digital products.</h2></div>${pageButton('projects','Explore all projects →','btn outline-light')}</div><div class="project-grid">${projects.map(([n,title,desc,tags],i)=>`<article class="project-card project-${i}"><div class="project-mock"><span>${n}</span><div class="mock-window"><i></i><i></i><i></i><b>${title}</b></div></div><div class="project-info"><span>${tags}</span><h3>${title}</h3><p>${desc}</p><button data-page="projects">View case study ↗</button></div></article>`).join('')}</div></section>
<section class="section tech-section"><div class="section-head centered"><span class="eyebrow">Technology expertise</span><h2>Modern tools. Thoughtful engineering.</h2><p>We choose dependable technologies that fit the problem, scale with ambition, and remain maintainable.</p></div><div class="tech-row">${['HTML5','CSS3','JavaScript','React','Node.js','Java','Python','PostgreSQL','AWS','Docker','GitHub','Figma'].map((x,i)=>`<div><span>${['◇','✣','JS','⚛','⬡','J','Py','▦','A','▱','⌘','F'][i]}</span><b>${x}</b></div>`).join('')}</div></section>
<section class="section why-section"><div class="why-copy"><span class="eyebrow">Why JNS InternNexus</span><h2>Built for progress you can see.</h2><p>One ecosystem connects mentorship, practical work, daily accountability, and career preparation.</p>${pageButton('about','Why learners choose us →','btn dark-btn')}</div><div class="benefit-grid">${[['01','Industry-oriented projects','Work through authentic product challenges, not isolated exercises.'],['02','Experienced mentors','Receive structured reviews, useful feedback, and personal guidance.'],['03','Centralized CRM','Manage tasks, attendance, work logs, meetings, and progress in one place.'],['04','Verified certification','Graduate with evaluated work, digital credentials, and a stronger portfolio.']].map(x=>`<article><span>${x[0]}</span><h3>${x[1]}</h3><p>${x[2]}</p></article>`).join('')}</div></section>
<section class="stats-section"><span class="eyebrow light">Our impact in numbers</span><div>${[['100+','Projects completed'],['500+','Interns trained'],['40+','Industry mentors'],['25+','Workshops conducted']].map(x=>`<article><strong>${x[0]}</strong><span>${x[1]}</span></article>`).join('')}</div></section>
<section class="section testimonial-section"><div class="quote-mark">“</div><blockquote>The JNS internship gave me what courses couldn’t—a real product, real deadlines, thoughtful mentor feedback, and the confidence to explain my work in interviews.</blockquote><div class="quote-person"><span>AK</span><div><strong>Ananya Krishnan</strong><small>Full Stack Intern · 2025</small></div><div class="stars">★★★★★</div></div></section>
<section class="section home-hub"><div class="section-heading"><div><span class="eyebrow">What’s happening at JNS</span><h2>Opportunities, knowledge,<br>and updates in one place.</h2></div><p>Explore active batches, upcoming learning events, career openings, announcements, and practical resources.</p></div><div class="home-hub-grid">${[['programs','Current batch','Full Stack Development · August 2026','24 seats · Filling fast','View batch'],['events','Upcoming workshop','Building AI Applications Responsibly','03 August · Online','Register now'],['careers','Career opportunity','Frontend Engineer · Product Team','Chennai · Hybrid','View opening'],['resources','Latest resource','The practical internship readiness guide','8 min read · Career','Read article'],['support','Announcement','Application deadline extended','Updated today · Important','View update'],['contact','Need guidance?','Talk to an internship coordinator','Response within 1 day','Contact HR']].map((x,i)=>`<article><span>${x[1]}</span><div class="hub-icon">${['◷','◇','↗','▤','!','◎'][i]}</div><h3>${x[2]}</h3><p>${x[3]}</p><button data-page="${x[0]}">${x[4]} →</button></article>`).join('')}</div></section>
<section class="newsletter"><div><span class="eyebrow light">Stay informed</span><h2>Useful updates. No clutter.</h2><p>Choose internship, event, career, service, or technical content updates.</p></div><form class="newsletter-form"><input type="email" required placeholder="Enter your email address"><select><option>All updates</option><option>Internships</option><option>Events</option><option>Careers</option><option>Technical resources</option></select><button class="btn light-btn">Subscribe →</button></form></section>`;

const moduleData={
 about:{kicker:'Inside JNS',title:'Technology with purpose.\nPeople with direction.',description:'Learn how JNS Private Limited brings innovation, practical learning, professional mentorship, and responsible growth together.',tabs:['Overview','Our Story','Mission & Vision','Leadership','Journey','Departments','Achievements','Life at JNS','Gallery','Policies','FAQ'],sections:[
  ['Company overview','A technology and talent-development company based in Chennai, serving students, professionals, startups, institutions, and businesses.',['Private Limited Company','Technology & Education','Pan-India service coverage','Students and Businesses']],
  ['Mission, vision & values','Reliable technology, meaningful industry exposure, and a culture founded on integrity.',['Innovation','Quality','Integrity','Collaboration','Learning','Accountability','Inclusion','Security']],
  ['Leadership & departments','Cross-functional leadership supported by specialized technology and people teams.',['Software Development','Artificial Intelligence','Cloud & DevOps','Cybersecurity','UI/UX Design','Quality Assurance','Human Resources','Training & Internship']],
  ['Our journey & achievements','A growing timeline of products delivered, people trained, partnerships created, and knowledge shared.',['100+ Projects Completed','500+ Interns Trained','25+ Workshops','15+ Technology Domains']],
  ['Life at JNS','A collaborative environment built for experimentation, feedback, wellbeing, and continuous development.',['Learning Culture','Team Collaboration','Mentor Sessions','Innovation Days','Career Growth','Flexible Work']],
  ['Office, gallery & facilities','Explore our development spaces, training rooms, meeting areas, and accessible facilities.',['Development Studio','Training Lab','Meeting Rooms','Collaboration Zones','Virtual Tour','Office Gallery']],
  ['Partners, responsibility & sustainability','Long-term partnerships, ethical operations, digital inclusion, and responsible technology practices.',['Technology Partners','Education Partners','Community Training','Green Operations','Data Responsibility','Accessibility']],
  ['Company profile & policies','Download verified company information and review the policies that guide our public services.',['Company Brochure','Privacy Policy','Terms & Conditions','Refund Policy','Accessibility Policy','Code of Conduct']]
 ]},
 services:{kicker:'Technology services',title:'From requirement to reliable result.',description:'Explore end-to-end design, engineering, AI, cloud, quality, consulting, training, and long-term support.',tabs:['Overview','Web','Mobile','Software','AI','Cloud','Security','UI/UX','Testing','DevOps','Training','Pricing','Quotation','FAQ'],sections:[
  ['Web development','Business sites, e-commerce, portals, PWAs, dashboards, APIs, and enterprise web platforms.',['Responsive Design','CMS Integration','Payment Gateway','Admin Dashboard','SEO','Analytics','Hosting','Maintenance']],
  ['Mobile application development','Native and cross-platform applications for Android, iOS, and the mobile web.',['Android','iOS','Flutter','React Native','Mobile UI/UX','Push Notifications','API Connectivity','Store Deployment']],
  ['Custom & enterprise software','Secure systems tailored to workflows, teams, data, and growth plans.',['CRM Systems','ERP Modules','Management Portals','Workflow Automation','Reporting','Role Access','Audit Logs','Integrations']],
  ['Artificial intelligence solutions','Responsible AI for support, analysis, recommendations, document intelligence, and automation.',['AI Chatbots','Workplace Assistants','Predictive Analytics','NLP','Recommendation Systems','Document AI','Safety Controls','Human Review']],
  ['Cloud, database & DevOps','Resilient infrastructure, deployment automation, observability, migration, and managed databases.',['AWS','Google Cloud','Firebase','Docker','CI/CD','Backups','Monitoring','Disaster Recovery']],
  ['Cybersecurity & quality assurance','Assessment, secure architecture, automated testing, performance validation, and clear reports.',['Vulnerability Assessment','Web Security','Authentication','Manual Testing','Automation Testing','Performance Testing','Risk Report','Remediation']],
  ['UI/UX design & consulting','Research-led product strategy, accessible experiences, prototypes, and scalable design systems.',['User Research','Wireframes','Prototypes','Design Systems','Usability Testing','Accessibility','Product Strategy','Figma']],
  ['Training, support & industry solutions','Corporate workshops, institution solutions, startup packages, maintenance, and dedicated support.',['Corporate Training','Institution Portals','Startup MVP','Basic Support','Standard Support','Premium Support','Dedicated Team','Knowledge Transfer']]
 ]},
 projects:{kicker:'Projects & portfolio',title:'Work built to solve real problems.',description:'Browse company, client, intern, AI, web, mobile, IoT, and research projects with technologies, outcomes, and case studies.',tabs:['All Projects','Company','Client','Intern','AI','Web Apps','Mobile','IoT','Research','Case Studies','Live Demos','Enquiry'],sections:[
  ['Featured digital platforms','Production-focused products with secure access, responsive experiences, operational reporting, and integrations.',['InternNexus CRM','Client Management System','Attendance Intelligence','Project Progress System']],
  ['AI & automation projects','Responsible intelligent systems designed around clear use cases and human oversight.',['AI Workplace Assistant','Document Intelligence','Smart Recommendations','Recruitment Assistant']],
  ['Web & mobile applications','Useful applications for organizations, students, field teams, and customers.',['Student Management','Service Portal','Mobile Learning App','Operations Dashboard']],
  ['IoT & smart systems','Connected prototypes combining sensors, cloud data, alerts, and actionable interfaces.',['Smart Bus Stop','Asset Monitoring','Attendance Device','Environment Monitor']],
  ['Intern innovation showcase','Mentor-reviewed capstone projects with documentation, demonstrations, and evaluation.',['Full Stack Capstone','AI Mini Project','Cybersecurity Lab','UI/UX Case Study']],
  ['Case studies & project enquiry','Understand the problem, process, solution, stack, results, and lessons—or request a similar solution.',['View Case Study','Watch Demo','View Screenshots','Technology Stack','GitHub Repository','Request Similar Solution']]
 ]},
 careers:{kicker:'Careers at JNS',title:'Do work that builds you, too.',description:'Explore current openings, fresher opportunities, campus hiring, benefits, recruitment stages, and life inside JNS.',tabs:['Openings','Departments','Fresher Jobs','Experienced Jobs','Campus Hiring','Walk-ins','Life at JNS','Benefits','Apply','Track Candidate','FAQ'],sections:[
  ['Current opportunities','Roles across engineering, product, design, people operations, training, sales, and support.',['Frontend Engineer','Backend Engineer','AI Engineer','UI/UX Designer','QA Engineer','HR Executive','Technical Mentor','Support Associate']],
  ['Ways to work with us','Find the arrangement and career stage that matches your goals.',['Full-time','Part-time','Internship','Contract','Remote','Hybrid','Onsite','Campus Hiring']],
  ['Recruitment process','A clear candidate journey with status visibility and timely communication.',['Explore Role','Submit Application','HR Screening','Technical Assessment','Interview','Offer','Document Verification','Onboarding']],
  ['Employee benefits','Support for professional development, wellbeing, recognition, and meaningful work.',['Learning Budget','Mentor Support','Flexible Work','Health & Wellbeing','Performance Recognition','Career Path','Team Events','Paid Leave']],
  ['Life and growth at JNS','Build with a collaborative team that values curiosity, ownership, inclusion, and feedback.',['Innovation Culture','Internal Mobility','Technical Sessions','Leadership Access','Project Ownership','Continuous Feedback']],
  ['Candidate tools','Save jobs, share openings, receive alerts, submit an application, and track progress.',['Job Alerts','Saved Jobs','Application Form','Resume Upload','Candidate Login','Track Application','Interview Schedule','Offer Documents']]
 ]},
 events:{kicker:'Events & learning',title:'Meet, learn, build, and share.',description:'Register for workshops, webinars, hackathons, technical seminars, project exhibitions, orientations, and training programs.',tabs:['Upcoming','Workshops','Webinars','Hackathons','Seminars','Training','Registration','Calendar','Recordings'],sections:[
  ['Upcoming experiences','Join expert-led sessions online or at our Chennai learning centre.',['AI Application Workshop','Full Stack Bootcamp','Cybersecurity Webinar','UI/UX Design Sprint']],
  ['Technology workshops','Hands-on guided sessions with practical exercises, resources, and participation certificates.',['Web Development','Artificial Intelligence','Cloud Deployment','Cybersecurity','Mobile Apps','Git & GitHub']],
  ['Hackathons & contests','Team-based problem solving with mentors, judging, recognition, and project showcases.',['Idea Submission','Team Registration','Mentor Hours','Live Evaluation','Awards','Project Exhibition']],
  ['Event services','Everything needed before, during, and after an event.',['Register Now','Add to Calendar','Download Brochure','Join Event','Share Event','Attendance','Certificate','View Recording']]
 ]},
 resources:{kicker:'Knowledge centre',title:'Useful knowledge, ready when you are.',description:'Read technical content, prepare for interviews, download learning resources, and follow company and industry news.',tabs:['Blogs','Tutorials','Articles','Interview Prep','Downloads','News','Saved','Newsletter'],sections:[
  ['Latest blogs','Practical writing from JNS engineers, mentors, HR professionals, and program alumni.',['Web Development','Artificial Intelligence','Cybersecurity','Cloud Computing','Career Guidance','Internship Tips']],
  ['Tutorials & technical articles','Step-by-step guides covering modern tools, engineering practices, and project development.',['React Fundamentals','REST API Design','Python for AI','Cloud Deployment','Security Basics','Testing Workflows']],
  ['Interview preparation','Structured resources for resumes, assessments, technical interviews, and project presentations.',['Resume Checklist','Aptitude Practice','Coding Questions','HR Questions','Mock Interviews','Portfolio Guide']],
  ['Download centre','Brochures, program syllabi, templates, guides, policies, and reference documents.',['Company Profile','Internship Brochure','Program Syllabus','Resume Template','Project Template','Event Brochure']],
  ['Company news & subscriptions','Follow announcements, product releases, batch updates, events, opportunities, and new articles.',['Company News','Product Updates','Batch Alerts','Career Alerts','Event Reminders','Email Newsletter']]
 ]},
 contact:{kicker:'Contact JNS',title:'How can we help you move forward?',description:'Reach the right team for services, internships, careers, partnerships, billing, or technical support.',tabs:['Contact','Directory','Callback','Consultation','Visit Us','Feedback','Complaints','Service Status'],sections:[
  ['Contact information','Connect with our teams Monday to Friday, 9:00 AM to 6:00 PM.',['Chennai, Tamil Nadu','hello@jns.com','+91 98765 43210','Business hours: 9 AM–6 PM']],
  ['Department directory','Choose the right destination so your request is handled quickly.',['General Enquiry','Sales & Services','Internship Coordinator','Human Resources','Accounts & Billing','Technical Support','Partnerships','Grievance Officer']],
  ['Ways to connect','Send an enquiry, request a callback, schedule a consultation, or plan an office visit.',['Contact Form','Request Callback','Schedule Consultation','WhatsApp','Email','Office Visit','Google Maps','Video Meeting']],
  ['Feedback, complaints & escalation','Structured acknowledgement, ownership, status updates, resolution, and satisfaction feedback.',['Submit Feedback','Register Complaint','Track Complaint','Escalate Request','Upload Evidence','Resolution History']]
 ]},
 support:{kicker:'Help & support',title:'Answers, assistance, and clear next steps.',description:'Search help articles, raise and track requests, contact HR, report technical issues, and review service status.',tabs:['Help Center','Raise Enquiry','Track Request','Contact HR','Technical Support','FAQ','Feedback','Complaints','Service Status'],sections:[
  ['Help center','Find step-by-step guidance for applications, payments, documents, CRM access, certificates, events, and careers.',['Getting Started','Applications','Payments','Documents','CRM Login','Attendance','Certificates','Events']],
  ['Support request management','Create a request with priority, category, description, attachment, and preferred contact method.',['Raise Ticket','Ticket ID','Email Updates','Priority','SLA','Assigned Team','Status Timeline','Resolution']],
  ['Specialist support','Reach the appropriate team for people, technology, accounts, privacy, or accessibility questions.',['Contact HR','Technical Support','Payment Support','Data Privacy','Accessibility Help','Emergency Escalation']],
  ['Frequently asked questions','Browse common questions or use the AI assistant for guided support.',['Internship FAQ','Application FAQ','Payment FAQ','CRM FAQ','Certificate FAQ','Career FAQ','Service FAQ','Event FAQ']]
 ]}
};
const modulePage=(state,id)=>{const p=moduleData[id]||moduleData.about;return `<section class="inner-hero module-hero-public"><div><span class="hero-kicker"><i></i> ${p.kicker}</span><h1>${p.title.replace('\n','<br>')}</h1><p>${p.description}</p><div class="hero-actions"><button class="btn primary" data-action="module-enquiry">Get started →</button><button class="btn hero-secondary" data-page="contact">Talk to our team</button></div></div><div class="module-index-card"><span>Explore this module</span><strong>${p.tabs.length} feature areas</strong><p>Every option is available below and through the top navigation.</p></div></section><nav class="module-tabs" aria-label="${p.kicker} sections">${p.tabs.map((x,i)=>`<button data-jump="section-${i%p.sections.length}">${x}</button>`).join('')}</nav><section class="module-content">${p.sections.map((s,i)=>`<article class="module-block ${i%2?'alt-block':''}" id="section-${i}"><div class="module-block-copy"><span class="eyebrow">${String(i+1).padStart(2,'0')} · ${p.kicker}</span><h2>${s[0]}</h2><p>${s[1]}</p><div class="module-actions"><button class="text-arrow" data-action="learn-more">Explore details →</button><button class="text-arrow muted-action" data-action="download">Download information ↓</button></div></div><div class="option-grid">${s[2].map((x,n)=>`<button data-option="${x}"><span>${['◇','↗','◎','✦'][n%4]}</span><b>${x}</b><small>View information and available actions</small><i>→</i></button>`).join('')}</div></article>`).join('')}</section>${id==='contact'||id==='support'?contactForm(id):faqSection()}`};
const contactForm=id=>`<section class="section enquiry-section"><div><span class="eyebrow">Send a request</span><h2>${id==='support'?'Raise a support request':'Tell us what you need'}</h2><p>Complete the form and the appropriate JNS team will respond within one business day.</p></div><form class="mini-enquiry"><label>Full name<input required name="name" placeholder="Your name"></label><label>Email address<input required type="email" name="email" placeholder="name@example.com"></label><label>Category<select name="category"><option>General enquiry</option><option>Internship</option><option>Services</option><option>Careers</option><option>Technical support</option><option>Payment support</option></select></label><label>Mobile number<input name="mobile" placeholder="+91"></label><label class="wide">Message<textarea required name="message" placeholder="How can we help?"></textarea></label><button class="btn primary">Submit request →</button></form></section>`;
const faqSection=()=>`<section class="section faq-section"><div class="section-head centered"><span class="eyebrow">Frequently asked questions</span><h2>Helpful answers, without the wait.</h2></div><div class="faq-list">${[['How do I choose the right option?','Use the module filters, compare available options, or ask the JNS AI assistant for a guided recommendation.'],['Can I speak with a JNS coordinator?','Yes. Use Contact Us, request a callback, or raise an enquiry and choose the relevant department.'],['Where can I track my request?','Applications have a dedicated public tracker. Service, support, event, and career requests receive their own reference ID.'],['Are documents and payments secure?','Public forms validate required data and route information securely. CRM access is created only after verification and approval.']].map((x,i)=>`<article><button data-faq aria-expanded="${i===0}"><span>${x[0]}</span><b>+</b></button><p ${i?'hidden':''}>${x[1]}</p></article>`).join('')}</div></section>`;
const programs=state=>`<section class="inner-hero module-hero-public"><div><span class="hero-kicker"><i></i> August 2026 intake</span><h1>Build skills employers<br>can actually see.</h1><p>Choose a mentor-guided pathway built around practical skills, professional workflows, and real deliverables.</p><div class="hero-actions"><button class="btn primary" data-page="apply">Apply for internship →</button><button class="btn hero-secondary" data-page="track">Track application</button></div></div><div class="module-index-card"><span>Internship ecosystem</span><strong>15 domains</strong><p>Eligibility, curriculum, batches, mentors, fees, projects, assessment, certification, and placement support.</p></div></section><nav class="module-tabs">${['Programs','Domains','Eligibility','Curriculum','Batches','Fees','Mentors','Benefits','Process','Projects','Assessment','Certificates','FAQ'].map((x,i)=>`<button data-jump="intern-${i}">${x}</button>`).join('')}</nav><section class="section" id="intern-0"><div class="filter-bar"><strong>${state.programs.length} programs available</strong><span>Filter: Domain · Duration · Mode · Fee · Eligibility · Start date · Status</span></div>${programCards(state.programs)}</section><section class="internship-features">${[
 ['Domains & eligibility','Choose from Full Stack, Frontend, Backend, Java, Python, AI, ML, Data Science, Cybersecurity, Cloud, DevOps, IoT, Mobile, UI/UX, and Testing.',['Degree & Department','Academic Year','Required Skills','Eligibility Checker']],
 ['Curriculum & batch schedule','Review weekly topics, learning outcomes, project milestones, batch dates, timing, mode, mentors, and seat availability.',['Week-by-week Curriculum','Calendar View','Online / Offline / Hybrid','Live Seat Count']],
 ['Fees, stipend & scholarships','See transparent program fees, taxes, due dates, refund rules, payment methods, stipend eligibility, discounts, and scholarships.',['UPI / Card / Net Banking','Payment Receipt','Scholarship Application','Fee Status']],
 ['Mentors & benefits','Meet domain mentors and understand the technical, professional, career, and platform benefits included.',['Mentor Profiles','Real-time Projects','Resume & Interview Support','CRM Progress Tracking']],
 ['Application to certification','A structured 13-step journey from exploring a program to final evaluation, documents, certification, and alumni access.',['Application & Documents','HR and Admin Approval','Mentor Assignment','Verified Certificate']],
 ['Projects, assessments & outcomes','Complete mentor-reviewed work evaluated through attendance, tasks, work logs, technical reviews, presentations, and feedback.',['Capstone Project','Technical Assessments','Performance Status','Recommendation Letter']]
].map((s,i)=>`<article id="intern-${i+1}"><div><span class="eyebrow">Internship module · 0${i+1}</span><h2>${s[0]}</h2><p>${s[1]}</p></div><div class="intern-feature-options">${s[2].map(x=>`<button data-option="${x}"><b>${x}</b><span>View details →</span></button>`).join('')}</div></article>`).join('')}</section>${faqSection()}`;
const details=state=>{const p=state.selectedProgram||state.programs[0];return p?`<section class="detail-hero"><button class="text-link" data-page="programs">← All internships</button><div><span class="hero-kicker"><i></i> ${p.domain}</span><h1>${p.title}</h1><p>${p.summary}</p><div class="detail-chips"><span>${p.duration}</span><span>${p.mode}</span><span>${p.location}</span><span>${p.seats} seats</span></div></div><aside><small>Program fee</small><strong>₹${money(p.fee)}</strong><span>Apply before ${p.deadline}</span><button class="btn primary" data-apply="${p.id}">Apply now →</button></aside></section><section class="section detail-grid"><div><span class="eyebrow">Program overview</span><h2>Learning outcomes</h2><p>Build an end-to-end project using professional workflows, mentor feedback, testing, documentation, and presentation.</p><h2>Technologies covered</h2><div class="program-tech">${String(p.technologies).split(',').map(x=>`<i>${x.trim()}</i>`).join('')}</div><h2>Eligibility</h2><p>Students and recent graduates with foundational knowledge, consistent availability, and curiosity.</p></div><aside class="detail-info">${[['Schedule','Monday–Friday'],['Mentorship','Weekly reviews'],['Certificate','Performance verified'],['Selection','HR review']].map(x=>`<div><small>${x[0]}</small><strong>${x[1]}</strong></div>`).join('')}</aside></section>`:'<div class="empty">Loading programs…</div>'};
const input=(name,label,type='text',required=false)=>type==='textarea'?`<label class="wide">${label}<textarea name="${name}"></textarea></label>`:`<label>${label}<input name="${name}" type="${type}" ${required?'required':''}></label>`;
const formSection=(n,title,html)=>`<section class="application-section"><div class="form-step">${n}</div><div class="form-section-body"><h2>${title}</h2><div class="application-grid">${html}</div></div></section>`;
const apply=state=>{const p=state.selectedProgram||state.programs[0];if(state.applicationResult)return `<section class="form-page success-page"><div class="success-mark">✓</div><span class="eyebrow">Application received</span><h1>Thank you for applying.</h1><p>Keep this reference safe and use it with your registered email to track status.</p><div class="reference-box"><small>Application ID</small><strong>${state.applicationResult.applicationId}</strong></div><button class="btn primary" data-page="track">Track application</button></section>`;return `<section class="form-page"><div class="form-intro"><span class="eyebrow">Internship admission</span><h1>Apply for ${p?.title||'an internship'}</h1><p>CRM access is created only after HR and final approval.</p></div><form class="public-form" id="applicationForm"><input type="hidden" name="program_id" value="${p?.id||''}">${formSection(1,'Personal details',input('full_name','Full name','text',true)+input('date_of_birth','Date of birth','date')+input('gender','Gender')+input('email','Email address','email',true)+input('mobile','Mobile number','tel',true)+input('alternate_mobile','Alternate mobile','tel')+input('address','Address','textarea')+input('city','City')+input('district','District')+input('state','State')+input('pin_code','PIN code'))}${formSection(2,'Academic details',input('college','College name')+input('university','University')+input('department','Department')+input('degree','Degree')+input('current_year','Current year')+input('semester','Semester')+input('registration_number','Registration number')+input('score','CGPA / Percentage')+input('graduation_year','Graduation year'))}${formSection(3,'Internship preferences',input('preferred_domain','Preferred domain')+input('duration','Duration')+input('start_date','Preferred start date','date')+input('mode','Mode')+input('location','Location')+input('experience','Previous experience','textarea')+input('skills','Skills','textarea')+input('interest_area','Area of interest','textarea'))}<section class="application-section"><div class="form-step">4</div><div class="form-section-body"><h2>Documents & consent</h2><div class="upload-grid">${['Resume','College ID','Identity Proof','Bonafide Certificate'].map((x,i)=>`<label class="upload-box">▤ <strong>${x}</strong><input type="file" name="document_${i}"><span>PDF, JPG or PNG</span></label>`).join('')}</div><label class="consent"><input type="checkbox" required> I accept the internship terms, privacy policy, payment policy, attendance rules, and code of conduct.</label></div></section><div class="form-submit"><span>Sent securely to the HR review queue.</span><button class="btn primary">Submit application →</button></div></form></section>`};
const track=state=>`<section class="track-page"><div class="track-copy"><span class="hero-kicker"><i></i> Public application portal</span><h1>Track your<br>application.</h1><p>Enter your reference and registered email. CRM credentials are issued only after approval.</p></div><form class="tracking-card" id="trackingForm"><span class="eyebrow">Secure status lookup</span><h2>Application status</h2><label>Application ID<input name="applicationId" placeholder="JNS-APP-2026-00001" required></label><label>Registered email<input name="email" type="email" required></label><button class="btn primary">Check status →</button><div class="tracking-error"></div>${state.trackingResult?`<div class="status-result"><span class="pill orange">${state.trackingResult.hrStatus}</span><h3>${state.trackingResult.applicantName}</h3><p>${state.trackingResult.program} · ${state.trackingResult.applicationDate}</p>${[['Payment',state.trackingResult.paymentStatus],['HR review',state.trackingResult.hrStatus],['Approval',state.trackingResult.approvalStatus],['Next action',state.trackingResult.requiredAction]].map(x=>`<div><span>${x[0]}</span><strong>${x[1]}</strong></div>`).join('')}</div>`:''}</form></section>`;

export function renderPublicSite(state){const body=state.publicPage==='home'?home(state):state.publicPage==='programs'?programs(state):state.publicPage==='details'?details(state):state.publicPage==='apply'?apply(state):state.publicPage==='track'?track(state):modulePage(state,state.publicPage);return shell(state,body)}
export function bindPublicSite(state,api,render,openLogin,toast){
 document.querySelectorAll('[data-page]').forEach(b=>b.onclick=()=>{const section=b.dataset.section;state.publicPage=b.dataset.page;if(section==='Apply for Internship'){state.publicPage='apply';state.applicationResult=null}else if(section==='Track Application'){state.publicPage='track'}scrollTo(0,0);render();if(section)setTimeout(()=>{const target=[...document.querySelectorAll('[data-option] b,.module-tabs button')].find(x=>x.textContent.trim()===section);target?.closest('article')?.scrollIntoView({behavior:'smooth',block:'start'})},0)});
 document.querySelectorAll('[data-crm]').forEach(b=>b.onclick=openLogin);
 document.querySelectorAll('[data-program]').forEach(b=>b.onclick=()=>{state.selectedProgram=state.programs.find(p=>p.id==b.dataset.program);state.publicPage='details';render()});
 document.querySelectorAll('[data-apply]').forEach(b=>b.onclick=()=>{state.selectedProgram=state.programs.find(p=>p.id==b.dataset.apply);state.applicationResult=null;state.publicPage='apply';render()});
 document.querySelector('.site-menu')?.addEventListener('click',e=>{const nav=document.querySelector('.site-links');nav.classList.toggle('open');e.currentTarget.setAttribute('aria-expanded',nav.classList.contains('open'))});
 document.querySelector('.announcement-close')?.addEventListener('click',e=>e.currentTarget.parentElement.remove());
 const modal=document.querySelector('.search-modal');document.querySelector('[data-search]')?.addEventListener('click',()=>{modal.hidden=false;modal.querySelector('input').focus()});document.querySelector('.search-close')?.addEventListener('click',()=>modal.hidden=true);
 modal?.querySelector('form').addEventListener('submit',e=>{e.preventDefault();const q=e.target.querySelector('input').value.toLowerCase();state.publicPage=q.includes('project')?'projects':q.includes('service')?'services':q.includes('career')?'careers':q.includes('event')?'events':q.includes('blog')||q.includes('resource')?'resources':q.includes('support')||q.includes('faq')?'support':'programs';render()});
 const notice=document.querySelector('.notice-panel');document.querySelector('[data-notice]')?.addEventListener('click',()=>notice.hidden=!notice.hidden);document.querySelector('[data-close-notice]')?.addEventListener('click',()=>notice.hidden=true);document.querySelector('.mark-read')?.addEventListener('click',()=>{notice.hidden=true;document.querySelector('.notification-button i').textContent='0';toast('All website notifications marked as read')});
 document.querySelectorAll('[data-jump]').forEach(b=>b.onclick=()=>document.getElementById(b.dataset.jump)?.scrollIntoView({behavior:'smooth',block:'start'}));
 document.querySelectorAll('[data-option],[data-action]').forEach(b=>b.onclick=()=>toast(`${b.dataset.option||'JNS team'}: more information is available through the enquiry and support options.`));
 document.querySelectorAll('[data-faq]').forEach(b=>b.onclick=()=>{const p=b.nextElementSibling;const open=p.hidden;p.hidden=!open;b.setAttribute('aria-expanded',open)});
 document.querySelector('.mini-enquiry')?.addEventListener('submit',e=>{e.preventDefault();toast('Your request has been submitted. The JNS team will contact you within one business day.');e.target.reset()});
 document.querySelector('.newsletter-form')?.addEventListener('submit',e=>{e.preventDefault();toast('Subscription confirmed. You will receive the JNS updates you selected.');e.target.reset()});
 document.querySelector('.ai-fab')?.addEventListener('click',()=>toast('JNS AI can guide you through internships, services, applications, payments, careers, events, and support.'));
 document.querySelector('#applicationForm')?.addEventListener('submit',async e=>{e.preventDefault();const button=e.target.querySelector('.form-submit button');button.disabled=true;button.textContent='Submitting securely…';const data=Object.fromEntries(new FormData(e.target));for(const [k,v] of Object.entries(data))if(v instanceof File)data[k]=v.name;try{state.applicationResult=await api.post('/public/applications',data);render();scrollTo(0,0)}catch(err){button.disabled=false;button.textContent='Submit application →';toast(err.message)}});
 document.querySelector('#trackingForm')?.addEventListener('submit',async e=>{e.preventDefault();const error=e.target.querySelector('.tracking-error');try{state.trackingResult=await api.post('/public/applications/track',Object.fromEntries(new FormData(e.target)));render()}catch(err){error.textContent=err.message}})
}
